pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('docker-test') {
                    sh 'docker build -t vignesh00501/myapp:v1 .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push vignesh00501/myapp:v1'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('docker-test') {
                    sh 'kubectl apply -f k8s-deployment.yaml'
                    sh 'kubectl apply -f k8s-service.yaml'
                }
            }
        }
    }
}

