pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('docker-test') {
                    sh 'docker build -t vignesh00501/myapp:v1 .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
               withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
        )]) {
            sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
            sh 'docker push vignesh00501/myapp:v1'
        }
    }
}

